package my.koinoxrista;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import my.koinoxrista.entities.Apartment;
import my.koinoxrista.entities.Building;
import my.koinoxrista.entities.Expense;
import my.koinoxrista.reports.KoinoxristaReport;
import my.koinoxrista.reports.ReceiptReport;
import my.koinoxrista.utils.SingleListSelectionModel;

public class CalculateForm extends javax.swing.JFrame {

    int _buildingId = 0;
    String _period = "";
    Building _building = null;
    float _koinoxristaSum = 0;
    float _heatingSum = 0;
    float _coownershipSum = 0;
    float _elevatorSum = 0;
    float _sum = 0;

    public CalculateForm() {
        initComponents();
        updateKoinoxristaTable();
    }

    public CalculateForm(int buildingId, String period) {
        _buildingId = buildingId;
        _period = period;
        initComponents();
        _building = Building.getById(buildingId);
        this.buildingInfoLabel.setText(_building.getDisplayName());
        this.titleLabel.setText("Υπολογισμός Κοινοχρήστων περιόδου " + period);
        this._koinoxristaSum = Expense.getCategorySum(_buildingId, 0, _period);
        this._heatingSum = Expense.getCategorySum(_buildingId, 1, _period);
        this._coownershipSum = Expense.getCategorySum(_buildingId, 2, _period);
        this._elevatorSum = Expense.getCategorySum(_buildingId, 3, _period);
        this._sum = _koinoxristaSum + _heatingSum + _coownershipSum + _elevatorSum;
        updateSumLabels();
        updateKoinoxristaTable();
    }

    private void updateSumLabels() {
        this.koinoxristaTotalLabel.setText(_koinoxristaSum + "");
        this.heatingTotalLabel.setText(_heatingSum + "");
        this.coownershipTotalLabel.setText(_coownershipSum + "");
        this.elevatorTotalLabel.setText(_elevatorSum + "");
        this.grandTotalLabel.setText(_sum + "");
    }

    public void updateKoinoxristaTable() {
        ArrayList<Apartment> apartments = Building.getApartments(_buildingId);
        DefaultTableModel dtm = this.buildTableModel(apartments);
        this.koinoxristaTable.setDefaultEditor(Object.class, null);
        this.koinoxristaTable.setSelectionModel(new SingleListSelectionModel());
        this.koinoxristaTable.setModel(dtm);
        dtm.fireTableDataChanged();
    }

    private DefaultTableModel buildTableModel(ArrayList<Apartment> apartments) {
        // names of columns
        Vector<String> columnNames = new Vector<String>();
        columnNames.add("ID");
        columnNames.add("Τύπος");
        columnNames.add("Κωδικός");
        columnNames.add("Χιλιοστά");
        columnNames.add("Ποσοστό Συμμετοχής");
        columnNames.add("Κοινόχρηστα");
        columnNames.add("Θέρμανση");
        columnNames.add("Συνιδιοκτησία");
        columnNames.add("Ανελκυστήρας");
        columnNames.add("Σύνολο");

        // data of the table
        float elevatorActualSum = 0;

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        for (Apartment apartment : apartments) {
            Vector<Object> vector = new Vector<Object>();

            float perMille = apartment.getPerMille();
            float percentage = perMille / 10;
            float factor = percentage / 100;
            float koinoxrista = factor * _koinoxristaSum;
            float heating = factor * _heatingSum;
            float coownership = factor * _coownershipSum;

            float elevator;
            if (apartment.getFloor() == 0 || apartment.getType().equals("store")) {
                elevator = 0;
            } else {
                elevator = factor * _elevatorSum;
            }
            elevatorActualSum += elevator;

            float sum = koinoxrista + heating + coownership + elevator;

            vector.add(apartment.getId());
            vector.add(Apartment.getTypeLiteral(apartment.getType()));
            vector.add(apartment.getCode());
            vector.add(perMille);
            vector.add(percentage);
            vector.add(koinoxrista);
            vector.add(heating);
            vector.add(coownership);
            vector.add(elevator);
            vector.add(sum);

            data.add(vector);
        }

        this.elevatorBalanceLabel.setText((_elevatorSum - elevatorActualSum) + "");

        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        return dtm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        koinoxristaTableContainer = new javax.swing.JScrollPane();
        koinoxristaTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        returnToBuildingsListButton = new javax.swing.JButton();
        buildingInfoLabel = new javax.swing.JLabel();
        printReceiptButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        koinoxristaTotalLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        heatingTotalLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        coownershipTotalLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        elevatorTotalLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        grandTotalLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        elevatorBalanceLabel = new javax.swing.JLabel();
        printKoinoxristaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Διαχείριση Κοινοχρήστων - Υπολογισμός Κοινοχρήστων");

        koinoxristaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Κωδικός Πολυκατοικίας", "Διεύθυνση", "Πόλη", "Ταχυδρομικός Κώδικας", "Αριθμός Διαμερισμάτων", "Ονοματεπώνυμο Διαχειριστή", "Τηλέφωνο Διαχειριστή"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        koinoxristaTableContainer.setViewportView(koinoxristaTable);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setText("Υπολογισμός Κοινοχρήστων");

        returnToBuildingsListButton.setText("Επιστροφή στη Λίστα Πολυκατοικιών");
        returnToBuildingsListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToBuildingsListButtonActionPerformed(evt);
            }
        });

        buildingInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        printReceiptButton.setText("Εκτύπωση Απόδειξης");
        printReceiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReceiptButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Σύνολο Κοινοχρήστων:");

        koinoxristaTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        koinoxristaTotalLabel.setText("0.00");

        jLabel3.setText("Σύνολο Θέρμανσης:");

        heatingTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heatingTotalLabel.setText("0.00");

        jLabel5.setText("Σύνολο Συνιδιοκτησίας:");

        coownershipTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coownershipTotalLabel.setText("0.00");

        jLabel7.setText("Σύνολο Ανελκυστήρα:");

        elevatorTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        elevatorTotalLabel.setText("0.00");

        jLabel9.setText("Γενικό Σύνολο:");

        grandTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        grandTotalLabel.setText("0.00");

        jLabel8.setText("Υπόλοιπο Ανελκυστήρα:");

        elevatorBalanceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        elevatorBalanceLabel.setForeground(new java.awt.Color(255, 0, 0));
        elevatorBalanceLabel.setText("0.00");

        printKoinoxristaButton.setText("Εκτύπωση Κοινοχρήστων");
        printKoinoxristaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printKoinoxristaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(koinoxristaTableContainer)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnToBuildingsListButton))
                    .addComponent(buildingInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(koinoxristaTotalLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(heatingTotalLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(coownershipTotalLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(elevatorTotalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(grandTotalLabel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(elevatorBalanceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(84, 426, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(printKoinoxristaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnToBuildingsListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildingInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(koinoxristaTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printKoinoxristaButton)
                    .addComponent(printReceiptButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(koinoxristaTotalLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heatingTotalLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coownershipTotalLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elevatorTotalLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grandTotalLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elevatorBalanceLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnToBuildingsListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToBuildingsListButtonActionPerformed
        BuildingsListForm form = new BuildingsListForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnToBuildingsListButtonActionPerformed

    private void printKoinoxristaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printKoinoxristaButtonActionPerformed
        String report = (new KoinoxristaReport(_buildingId, _period)).generate();
        PrintPreviewDialog form = new PrintPreviewDialog(report);
        form.setVisible(true);
    }//GEN-LAST:event_printKoinoxristaButtonActionPerformed

    private void printReceiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReceiptButtonActionPerformed
        int row = this.koinoxristaTable.getSelectedRow();

        // Check if user has actually selected a table item
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Παρακαλώ επιλέξτε ένα στοιχείο του πίνακα για έκδοση απόδειξης πληρωμής.",
                    "Σφάλμα",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            // Get currently selected apartment ID
            int apartmentId = (int) this.koinoxristaTable.getModel().getValueAt(row, 0);
            float amount = (float) this.koinoxristaTable.getModel().getValueAt(row, 9);
            String report = (new ReceiptReport(_buildingId, apartmentId, amount, _period)).generate();
            PrintPreviewDialog form = new PrintPreviewDialog(report);
            form.setVisible(true);
        }
    }//GEN-LAST:event_printReceiptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildingInfoLabel;
    private javax.swing.JLabel coownershipTotalLabel;
    private javax.swing.JLabel elevatorBalanceLabel;
    private javax.swing.JLabel elevatorTotalLabel;
    private javax.swing.JLabel grandTotalLabel;
    private javax.swing.JLabel heatingTotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTable koinoxristaTable;
    private javax.swing.JScrollPane koinoxristaTableContainer;
    private javax.swing.JLabel koinoxristaTotalLabel;
    private javax.swing.JButton printKoinoxristaButton;
    private javax.swing.JButton printReceiptButton;
    private javax.swing.JButton returnToBuildingsListButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
