package my.koinoxrista;

import my.koinoxrista.utils.SqliteConnection;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import my.koinoxrista.entities.Building;
import my.koinoxrista.entities.Expense;
import my.koinoxrista.reports.ExpensesReport;
import my.koinoxrista.utils.SingleListSelectionModel;

public class ExpensesListForm extends javax.swing.JFrame {

    int _buildingId = 0;
    Building _building = null;

    public ExpensesListForm() {
        initComponents();
        updateExpensesTable();
    }

    public ExpensesListForm(int buildingId) {
        _buildingId = buildingId;
        initComponents();
        _building = Building.getById(buildingId);
        this.buildingInfoLabel.setText(_building.getDisplayName());
        updateExpensesTable();
    }

    public void updateExpensesTable() {
        Connection connection = SqliteConnection.getConnection();

        String query = "select * from expenses where building_id = ?";
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            pstmt = connection.prepareStatement(query);
            pstmt.setInt(1, _buildingId);
            rs = pstmt.executeQuery();
            DefaultTableModel dtm = buildTableModel(rs);
            this.expensesTable.setDefaultEditor(Object.class, null);
            this.expensesTable.setSelectionModel(new SingleListSelectionModel());
            this.expensesTable.setModel(dtm);
            dtm.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public void updateExpensesTable(String period) {
        Connection connection = SqliteConnection.getConnection();

        String query = "select * from expenses where building_id = ? and period like ?";
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            pstmt = connection.prepareStatement(query);
            pstmt.setInt(1, _buildingId);
            pstmt.setString(2, period);
            rs = pstmt.executeQuery();
            DefaultTableModel dtm = buildTableModel(rs);
            this.expensesTable.setDefaultEditor(Object.class, null);
            this.expensesTable.setSelectionModel(new SingleListSelectionModel());
            this.expensesTable.setModel(dtm);
            dtm.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public static DefaultTableModel buildTableModel(ResultSet rs)
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        columnNames.add("ID Εξόδου");
        columnNames.add("Κωδικός Πολυκατοικίας");
        columnNames.add("Κατηγορία");
        columnNames.add("Περιγραφή");
        columnNames.add("Περίοδος");
        columnNames.add("Ποσό");

        // data of the table
        int columnCount = metaData.getColumnCount();
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();

            vector.add(rs.getInt("id"));
            vector.add(rs.getInt("building_id"));
            vector.add(Expense.getCategoryLiteral(rs.getInt("category")));
            vector.add(rs.getString("description"));
            vector.add(rs.getString("period"));
            vector.add(rs.getFloat("amount"));

            data.add(vector);
        }

        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);

        return dtm;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expensesTableContainer = new javax.swing.JScrollPane();
        expensesTable = new javax.swing.JTable();
        newRecordButton = new javax.swing.JButton();
        editRecordButton = new javax.swing.JButton();
        deleteRecordButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        returnToBuildingsListButton = new javax.swing.JButton();
        buildingInfoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        periodTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        displayAllButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Διαχείριση Κοινοχρήστων - Λίστα Εξόδων");

        expensesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Κωδικός Πολυκατοικίας", "Διεύθυνση", "Πόλη", "Ταχυδρομικός Κώδικας", "Αριθμός Διαμερισμάτων", "Ονοματεπώνυμο Διαχειριστή", "Τηλέφωνο Διαχειριστή"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expensesTableContainer.setViewportView(expensesTable);

        newRecordButton.setText("Νέα Εγγραφή");
        newRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRecordButtonActionPerformed(evt);
            }
        });

        editRecordButton.setText("Επεξεργασία Εγγραφής");
        editRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRecordButtonActionPerformed(evt);
            }
        });

        deleteRecordButton.setText("Διαγραφή Εγγραφής");
        deleteRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setText("Λίστα Εξόδων");

        returnToBuildingsListButton.setText("Επιστροφή στη Λίστα Πολυκατοικιών");
        returnToBuildingsListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToBuildingsListButtonActionPerformed(evt);
            }
        });

        buildingInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setText("Εισάγετε περίοδο για εμφάνιση εξόδων:");

        searchButton.setText("Αναζήτηση");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        displayAllButton.setText("Εμφάνιση όλων");
        displayAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllButtonActionPerformed(evt);
            }
        });

        printButton.setText("Εκτύπωση");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(expensesTableContainer)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnToBuildingsListButton))
                    .addComponent(buildingInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(periodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteRecordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editRecordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnToBuildingsListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildingInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(periodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(displayAllButton)
                    .addComponent(printButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expensesTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRecordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editRecordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteRecordButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRecordButtonActionPerformed
        ExpenseDetailsForm form = new ExpenseDetailsForm(0, _buildingId, this);
        form.setVisible(true);
    }//GEN-LAST:event_newRecordButtonActionPerformed

    private void editRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRecordButtonActionPerformed
        int row = this.expensesTable.getSelectedRow();

        // Check if user has actually selected an apartment to edit
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Παρακαλώ επιλέξτε έξοδο για επεξεργασία.",
                    "Σφάλμα",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            // Get currently selected apartment ID
            int expense_id = (int) this.expensesTable.getModel().getValueAt(row, 0);
            ExpenseDetailsForm form = new ExpenseDetailsForm(expense_id, _buildingId, this);
            form.setVisible(true);
        }
    }//GEN-LAST:event_editRecordButtonActionPerformed

    private void deleteRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecordButtonActionPerformed
        int row = this.expensesTable.getSelectedRow();

        // Check if user has actually selected an expense to delete
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Παρακαλώ επιλέξτε έξοδο για διαγραφή.",
                    "Σφάλμα",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            int result = JOptionPane.showConfirmDialog(this,
                    "Είστε βέβαιοι πως επιθυμείτε να διαγράψετε το επιλεγμένο έξοδο;\n"
                    + "Η ενέργεια αυτή δεν μπορεί να αναιρεθεί.",
                    "Επιβεβαίωση Διαγραφής",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == 0) {
                int expense_id = (int) this.expensesTable.getModel().getValueAt(row, 0);
                String query = "delete from expenses where id = ?";
                Connection connection = SqliteConnection.getConnection();
                PreparedStatement pstmt = null;

                try {
                    pstmt = connection.prepareStatement(query);
                    pstmt.setInt(1, expense_id);
                    pstmt.executeUpdate();
                } catch (Exception ex) {
                    ex.printStackTrace();
                } finally {
                    try {
                        if (pstmt != null) {
                            pstmt.close();
                        }
                        if (connection != null) {
                            connection.close();
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }

                this.updateExpensesTable();
            }
        }
    }//GEN-LAST:event_deleteRecordButtonActionPerformed

    private void returnToBuildingsListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToBuildingsListButtonActionPerformed
        BuildingsListForm form = new BuildingsListForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnToBuildingsListButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String period = this.periodTextField.getText();
        if (period.equals("")) {
            this.updateExpensesTable();
        } else {
            this.updateExpensesTable(period);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void displayAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllButtonActionPerformed
        this.periodTextField.setText("");
        this.updateExpensesTable();
    }//GEN-LAST:event_displayAllButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        String report = (new ExpensesReport(_buildingId, this.periodTextField.getText())).generate();
        PrintPreviewDialog form = new PrintPreviewDialog(report);
        form.setVisible(true);
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpensesListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpensesListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpensesListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpensesListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpensesListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildingInfoLabel;
    private javax.swing.JButton deleteRecordButton;
    private javax.swing.JButton displayAllButton;
    private javax.swing.JButton editRecordButton;
    private javax.swing.JTable expensesTable;
    private javax.swing.JScrollPane expensesTableContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newRecordButton;
    private javax.swing.JTextField periodTextField;
    private javax.swing.JButton printButton;
    private javax.swing.JButton returnToBuildingsListButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
